"""
=============================================================================
ADAPTIV HEALTH - Risk Assessment Model
=============================================================================
Stores AI-generated cardiovascular risk evaluations.
Core output from the ComputeRiskScore algorithm (Design Doc Section 5).
=============================================================================
"""

from sqlalchemy import Column, Integer, Float, String, DateTime, ForeignKey, Enum, Text, Boolean, Index
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from app.database import Base
import enum
import json


class RiskLevel(str, enum.Enum):
    """
    Risk levels from ComputeRiskScore algorithm (Design Doc Section 5).
    
    Score Mapping:
    - LOW: 0.0 - 0.49 → Safe to continue activity
    - MODERATE: 0.50 - 0.79 → Recommend slower pace or rest
    - HIGH: 0.80 - 1.0 → DANGER - Stop immediately, trigger alert
    """
    LOW = "low"
    MODERATE = "moderate"
    HIGH = "high"


class AssessmentType(str, enum.Enum):
    """Types of risk assessments."""
    REALTIME = "realtime"    # Edge AI instant assessment (<160ms)
    PERIODIC = "periodic"    # Regular interval checks
    DAILY = "daily"          # Daily summary analysis
    WEEKLY = "weekly"        # Weekly trend analysis
    SESSION = "session"      # Post-workout assessment
    MANUAL = "manual"        # Clinician-triggered assessment


class RiskAssessment(Base):
    """
    Risk Assessment from Data Dictionary (Section 4.1).
    
    Stores AI evaluations of cardiovascular risk based on:
    - Real-time vital signs (HR, SpO2, HRV)
    - Historical patterns and trends
    - User baseline metrics
    - Age and medical history factors
    
    Generated by:
    - Edge AI (TensorFlow Lite) - Real-time assessments during activity
    - Cloud AI (TensorFlow) - Deep analysis for daily/weekly assessments
    
    Algorithm (ComputeRiskScore):
        input_vector = NORMALIZE([heart_rate, spo2, hrv, age, baseline_HR])
        risk_score = TFLite_Model.PREDICT(input_vector)  # 0 → 1
        
        if risk_score >= 0.80: return HIGH
        elif risk_score >= 0.50: return MODERATE
        else: return LOW
    """
    
    __tablename__ = "risk_assessments"
    
    # -------------------------------------------------------------------------
    # Primary Key
    # -------------------------------------------------------------------------
    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    
    # -------------------------------------------------------------------------
    # Foreign Key
    # -------------------------------------------------------------------------
    user_id = Column(
        Integer,
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )
    
    # -------------------------------------------------------------------------
    # Risk Classification (AI Output)
    # -------------------------------------------------------------------------
    risk_level = Column(Enum(RiskLevel), nullable=False, index=True)
    risk_score = Column(Float, nullable=False)  # 0.0 to 1.0
    
    # -------------------------------------------------------------------------
    # Assessment Type and Source
    # -------------------------------------------------------------------------
    assessment_type = Column(Enum(AssessmentType), default=AssessmentType.REALTIME, nullable=False)
    generated_by = Column(String(20), default="edge_ai")  # edge_ai, cloud_ai, clinician
    
    # -------------------------------------------------------------------------
    # Input Values (What the AI Analyzed)
    # -------------------------------------------------------------------------
    input_heart_rate = Column(Integer, nullable=True)
    input_spo2 = Column(Float, nullable=True)
    input_hrv = Column(Float, nullable=True)
    input_blood_pressure_sys = Column(Integer, nullable=True)
    input_blood_pressure_dia = Column(Integer, nullable=True)
    
    # -------------------------------------------------------------------------
    # User Context
    # -------------------------------------------------------------------------
    user_age = Column(Integer, nullable=True)
    baseline_heart_rate = Column(Integer, nullable=True)
    max_heart_rate = Column(Integer, nullable=True)
    current_activity_phase = Column(String(20), nullable=True)  # resting, active, recovery
    
    # -------------------------------------------------------------------------
    # AI Model Information
    # -------------------------------------------------------------------------
    model_name = Column(String(100), nullable=True)  # e.g., "risk_classifier_v2"
    model_version = Column(String(50), nullable=True)  # e.g., "2.1.0"
    confidence = Column(Float, nullable=True)  # Model confidence in prediction (0-1)
    inference_time_ms = Column(Float, nullable=True)  # How long inference took
    
    # -------------------------------------------------------------------------
    # Explanation (Interpretable AI - SRS Requirement)
    # -------------------------------------------------------------------------
    # JSON string containing factors that contributed to the risk score
    risk_factors_json = Column(Text, nullable=True)
    primary_concern = Column(String(100), nullable=True)  # Main risk factor
    
    # -------------------------------------------------------------------------
    # Action Taken
    # -------------------------------------------------------------------------
    alert_triggered = Column(Boolean, default=False)
    alert_id = Column(Integer, nullable=True)  # Link to Alert if one was created
    recommendation_generated = Column(Boolean, default=False)
    recommendation_id = Column(Integer, nullable=True)  # Link to Recommendation
    
    # -------------------------------------------------------------------------
    # Related Activity Session
    # -------------------------------------------------------------------------
    activity_session_id = Column(Integer, nullable=True)
    
    # -------------------------------------------------------------------------
    # Timestamps
    # -------------------------------------------------------------------------
    assessment_date = Column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
        index=True
    )
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    
    # -------------------------------------------------------------------------
    # Relationship
    # -------------------------------------------------------------------------
    user = relationship("User", back_populates="risk_assessments")
    
    # -------------------------------------------------------------------------
    # Indexes
    # -------------------------------------------------------------------------
    __table_args__ = (
        Index('idx_risk_user_date', 'user_id', 'assessment_date'),
        Index('idx_risk_level', 'risk_level'),
        Index('idx_risk_score', 'risk_score'),
        Index('idx_risk_alert', 'alert_triggered'),
    )
    
    # -------------------------------------------------------------------------
    # Methods
    # -------------------------------------------------------------------------
    def __repr__(self) -> str:
        return f"<RiskAssessment(id={self.id}, user_id={self.user_id}, level={self.risk_level.value}, score={self.risk_score:.2f})>"
    
    @property
    def is_critical(self) -> bool:
        """Check if this is a critical/high-risk assessment."""
        return self.risk_level == RiskLevel.HIGH or self.risk_score >= 0.8
    
    @property
    def requires_alert(self) -> bool:
        """Determine if this assessment should trigger an alert."""
        return self.risk_score >= 0.8
    
    @property
    def requires_intervention(self) -> bool:
        """Check if user should modify their activity."""
        return self.risk_score >= 0.5
    
    def get_recommendation_text(self) -> str:
        """Get human-readable recommendation based on risk level."""
        recommendations = {
            RiskLevel.LOW: "Safe to continue activity at current intensity. Keep monitoring.",
            RiskLevel.MODERATE: "Consider reducing intensity or taking a short break. Monitor closely.",
            RiskLevel.HIGH: "⚠️ STOP activity immediately. Rest and monitor symptoms. Seek help if needed."
        }
        return recommendations.get(self.risk_level, "Please consult a healthcare provider.")
    
    def set_risk_factors(self, factors: dict) -> None:
        """
        Store risk factors as JSON.
        
        Args:
            factors: Dictionary of risk factors and their weights
                     e.g., {"high_heart_rate": 0.4, "low_spo2": 0.3}
        """
        self.risk_factors_json = json.dumps(factors)
    
    def get_risk_factors(self) -> dict:
        """
        Retrieve risk factors from JSON storage.
        
        Returns:
            Dictionary of risk factors
        """
        if self.risk_factors_json:
            return json.loads(self.risk_factors_json)
        return {}
    
    @staticmethod
    def calculate_risk_level(score: float) -> RiskLevel:
        """
        Determine risk level from score.
        
        Args:
            score: Risk score from 0 to 1
            
        Returns:
            RiskLevel enum value
        """
        if score >= 0.80:
            return RiskLevel.HIGH
        elif score >= 0.50:
            return RiskLevel.MODERATE
        else:
            return RiskLevel.LOW
    
    def to_dict(self) -> dict:
        """Convert to dictionary for API responses."""
        return {
            "id": self.id,
            "user_id": self.user_id,
            "risk_level": self.risk_level.value,
            "risk_score": self.risk_score,
            "assessment_type": self.assessment_type.value,
            "input_values": {
                "heart_rate": self.input_heart_rate,
                "spo2": self.input_spo2,
                "hrv": self.input_hrv,
                "blood_pressure_systolic": self.input_blood_pressure_sys,
                "blood_pressure_diastolic": self.input_blood_pressure_dia,
            },
            "model_info": {
                "name": self.model_name,
                "version": self.model_version,
                "confidence": self.confidence,
            },
            "risk_factors": self.get_risk_factors(),
            "primary_concern": self.primary_concern,
            "recommendation": self.get_recommendation_text(),
            "alert_triggered": self.alert_triggered,
            "assessment_date": self.assessment_date.isoformat() if self.assessment_date else None
        }